### ISSUE TITLE
Kotlin formatter

### ISSUE THREAD

**Issue by esafirm** [fwcd/KotlinLanguageServer#27]
We can't reformat our code. Maybe we can use [ktlint](https://github.com/shyiko/ktlint)

```
There is no document formatter for 'kotlin'-files installed.
```

**Comment by fwcd** [comment]
This will be added in a future release. (A pull request would be really awesome too, if you are interested in contributing)

To add some other notable reference implementations (of Kotlin formatters):
* https://github.com/JetBrains/kotlin-eclipse/tree/master/kotlin-eclipse-ui/src/org/jetbrains/kotlin/ui/formatter
* https://github.com/JetBrains/kotlin/tree/master/idea/formatter/src/org/jetbrains/kotlin/idea

**Comment by Tadaboody** [comment]
Where in the code will this linter need to be integrated?

**Comment by fwcd** [comment]
@Tadaboody Essentially, this function would need to be implemented:

https://github.com/fwcd/KotlinLanguageServer/blob/116589a325f6ca7799a8a84df90c1f4a9110dd05/src/main/kotlin/org/javacs/kt/KotlinTextDocumentService.kt#L89

It might be a good idea to move all formatting code into a separate subpackage of org.javacs.kt (as with the other features).

**Comment by esafirm** [comment]
Great job 👍
