### ISSUE TITLE
Support Hover on declarations

### ISSUE THREAD

**Issue by fwcd** [fwcd/KotlinLanguageServer#41]
Show type information upon hover on a declaration.

![Demo](https://user-images.githubusercontent.com/30873659/43327670-adf5ee64-91c4-11e8-8d4a-694c10ea2c2a.gif)

**Comment by Strum355** [comment]
This doesnt seem to be working for me on latest commit.

**Comment by fwcd** [comment]
@Strum355 Could you please paste the output log?

**Comment by Strum355** [comment]
```
[INFO]      async0      main    Hovering at file:///home/noah/Kotlin/main.kt 5:8
[INFO]      async0      main    Re-parsing main.kt 5:5-6:26
[INFO]      async0      main    Compiling var x = something(10)
[INFO]      async0      main    Finished in 27 ms
```

```kt
fun something(x: Int): String {
    return "test ${x}"
}

fun main(args: Array<String>) {
    var x = something(10)
    println(x)
}
```

Hovering over `x` in the println call gives the correct hover, however hovering over `x` in the previous line gives nothing. Unfortunately this is all the log says. Is there a more verbose log i should enable?

**Comment by fwcd** [comment]
@Strum355 Ok, I will look into this soon. Sometimes the LS fails to infer a type, but should show an `[ERROR]` type upon hover nevertheless.

**Comment by fwcd** [comment]
@Strum355 I can't reproduce the issue. The language server does not throw a stack trace either according to your log, so I suppose you are running an older version. You could try building the the repo yourself, because the version on the VSCode marketplace might not have this feature yet.

![image](https://user-images.githubusercontent.com/30873659/43599258-b7261b88-968f-11e8-8025-a6b3a7256d29.png)

**Comment by Strum355** [comment]
Ah yea it works from master, marketplace one must be an older one then. I dont remember if i was running from master in Extension Development mode or not at the time that I noticed it wasnt working. My bad ^^
