### ISSUE TITLE
Find Sources of Compiled Symbol

### ISSUE THREAD

**Issue by musiKk** [fwcd/KotlinLanguageServer#55]
When I try to go to a compiled symbol, I get exactly the same error as #23.

I used a common class (`java.util.ArrayList`) and the file path shown in the error message does exist on my system so the general setup is correct but the feature for loading the file is not working (it also works out of the box with vscode-java).

Example:

```
package test

import java.util.ArrayList
```

Put cursor on "ArrayList" and hit F12.

**Actual result**: The result is an error as described above.

**Expected result**: The Java sources for the class are shown.

Version is the most current in the extension marketplace: 0.1.8.

**Comment by fwcd** [comment]
This feature has already been implemented in #23, but is currently disabled due to a severe bug that silently crashes the language server.

See #45.
