### ISSUE TITLE
'as' as a soft keyword

### ISSUE THREAD

**Issue by KadenGordon** [fwcd/KotlinLanguageServer#68]
'as' is a keyword in import statements, and ideally is highlighted a different color than the imported class, probably the same color as the 'import' keyword.

**Comment by fwcd** [comment]
@KadenGordon `as` is already registered as a soft keyword, but according to your description you probably meant a hard keyword. I will look into this soon.

For reference, the [official keyword list](https://kotlinlang.org/docs/reference/keyword-reference.html) also considers `as` to be a hard keyword.

**Comment by fwcd** [comment]
Version 0.1.11 has been released, so the fix should be available on the marketplace.
