### ISSUE TITLE
Kotlin 1.3 support

### ISSUE THREAD

**Issue by TTSKarlsson** [fwcd/KotlinLanguageServer#78]
In gradle I'm loading the current stable kotlin version 1.3.11 and setting the apiVersion and languageVersion to "1.3" but I still get [kotlin] The feature "<insert 1.3 feature here>" is only available since language version 1.3 [UNSUPPORTED_FEATURE] error in the editor.

Gradle still compiles and runs the code without problem, but the errors in the editor breaks autocompletion and such.

Is there any way to set the api version that this extension is using, or at least make it use the current version?

**Comment by TTSKarlsson** [comment]
To reproduce you can try with
inline class name()

**Comment by fwcd** [comment]
@TTSKarlsson Kotlin 1.3 support is planned and seems to be addressed by [a fork](https://github.com/norefle/KotlinLanguageServer/tree/kotlin-1.3.11).

**Comment by TTSKarlsson** [comment]
Nice! I'll just wait until it's official. 👍

**Comment by TTSKarlsson** [comment]
I caved and compiled and installed the fork. It still has the same problem. Saving a little time for others reading this.

**Comment by Strum355** [comment]
Think the branch got merged there very recently, just gotta wait for the next release

**Comment by fwcd** [comment]
Yup, I am going to close this issue since the new version is merged.
