### ISSUE TITLE
Should this project be the authoritative location for kotlin lang server?

### ISSUE THREAD

**Issue by georgewfraser** [fwcd/KotlinLanguageServer#8]
@fwcd If you expect that you will stick with this project, I will be happy to change my readme to redirect to this repo like [this](https://github.com/georgewfraser/kotlin-language-server/pull/4/files).

If you're still unsure if you're going to stick with it, then I can hold off on doing this.

Also I am happy to give advice about the code structure if needed.

**Comment by fwcd** [comment]
@georgewfraser I will continue to actively work on this repo, so this looks like a good solution. When I have any questions about the code I will ask you, thank you.

Closing this issue as resolved.
